/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RadioRouteImport } from './routes/radio'
import { Route as MastheadRouteImport } from './routes/masthead'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BestNewRouteImport } from './routes/best-new'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReviewsIndexRouteImport } from './routes/reviews.index'
import { Route as ListsIndexRouteImport } from './routes/lists.index'
import { Route as FeaturesIndexRouteImport } from './routes/features.index'
import { Route as ReviewsSlugRouteImport } from './routes/reviews.$slug'
import { Route as ListsSlugRouteImport } from './routes/lists.$slug'
import { Route as FeaturesSlugRouteImport } from './routes/features.$slug'
import { Route as AdminSubscribersRouteImport } from './routes/admin.subscribers'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminListsRouteImport } from './routes/admin.lists'
import { Route as AdminFeaturesRouteImport } from './routes/admin.features'
import { Route as AdminContributorsRouteImport } from './routes/admin.contributors'
import { Route as AdminReviewsIndexRouteImport } from './routes/admin.reviews.index'
import { Route as AdminReviewsImportRouteImport } from './routes/admin.reviews.import'
import { Route as AdminReviewsIdRouteImport } from './routes/admin.reviews.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RadioRoute = RadioRouteImport.update({
  id: '/radio',
  path: '/radio',
  getParentRoute: () => rootRouteImport,
} as any)
const MastheadRoute = MastheadRouteImport.update({
  id: '/masthead',
  path: '/masthead',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BestNewRoute = BestNewRouteImport.update({
  id: '/best-new',
  path: '/best-new',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsIndexRoute = ReviewsIndexRouteImport.update({
  id: '/reviews/',
  path: '/reviews/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsIndexRoute = ListsIndexRouteImport.update({
  id: '/lists/',
  path: '/lists/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesIndexRoute = FeaturesIndexRouteImport.update({
  id: '/features/',
  path: '/features/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsSlugRoute = ReviewsSlugRouteImport.update({
  id: '/reviews/$slug',
  path: '/reviews/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsSlugRoute = ListsSlugRouteImport.update({
  id: '/lists/$slug',
  path: '/lists/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesSlugRoute = FeaturesSlugRouteImport.update({
  id: '/features/$slug',
  path: '/features/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubscribersRoute = AdminSubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminListsRoute = AdminListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeaturesRoute = AdminFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContributorsRoute = AdminContributorsRouteImport.update({
  id: '/contributors',
  path: '/contributors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsIndexRoute = AdminReviewsIndexRouteImport.update({
  id: '/reviews/',
  path: '/reviews/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsImportRoute = AdminReviewsImportRouteImport.update({
  id: '/reviews/import',
  path: '/reviews/import',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsIdRoute = AdminReviewsIdRouteImport.update({
  id: '/reviews/$id',
  path: '/reviews/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/archive': typeof ArchiveRoute
  '/auth': typeof AuthRoute
  '/best-new': typeof BestNewRoute
  '/contact': typeof ContactRoute
  '/masthead': typeof MastheadRoute
  '/radio': typeof RadioRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/contributors': typeof AdminContributorsRoute
  '/admin/features': typeof AdminFeaturesRoute
  '/admin/lists': typeof AdminListsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/features/$slug': typeof FeaturesSlugRoute
  '/lists/$slug': typeof ListsSlugRoute
  '/reviews/$slug': typeof ReviewsSlugRoute
  '/features/': typeof FeaturesIndexRoute
  '/lists/': typeof ListsIndexRoute
  '/reviews/': typeof ReviewsIndexRoute
  '/admin/reviews/$id': typeof AdminReviewsIdRoute
  '/admin/reviews/import': typeof AdminReviewsImportRoute
  '/admin/reviews/': typeof AdminReviewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/archive': typeof ArchiveRoute
  '/auth': typeof AuthRoute
  '/best-new': typeof BestNewRoute
  '/contact': typeof ContactRoute
  '/masthead': typeof MastheadRoute
  '/radio': typeof RadioRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/contributors': typeof AdminContributorsRoute
  '/admin/features': typeof AdminFeaturesRoute
  '/admin/lists': typeof AdminListsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/features/$slug': typeof FeaturesSlugRoute
  '/lists/$slug': typeof ListsSlugRoute
  '/reviews/$slug': typeof ReviewsSlugRoute
  '/features': typeof FeaturesIndexRoute
  '/lists': typeof ListsIndexRoute
  '/reviews': typeof ReviewsIndexRoute
  '/admin/reviews/$id': typeof AdminReviewsIdRoute
  '/admin/reviews/import': typeof AdminReviewsImportRoute
  '/admin/reviews': typeof AdminReviewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/archive': typeof ArchiveRoute
  '/auth': typeof AuthRoute
  '/best-new': typeof BestNewRoute
  '/contact': typeof ContactRoute
  '/masthead': typeof MastheadRoute
  '/radio': typeof RadioRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/contributors': typeof AdminContributorsRoute
  '/admin/features': typeof AdminFeaturesRoute
  '/admin/lists': typeof AdminListsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/features/$slug': typeof FeaturesSlugRoute
  '/lists/$slug': typeof ListsSlugRoute
  '/reviews/$slug': typeof ReviewsSlugRoute
  '/features/': typeof FeaturesIndexRoute
  '/lists/': typeof ListsIndexRoute
  '/reviews/': typeof ReviewsIndexRoute
  '/admin/reviews/$id': typeof AdminReviewsIdRoute
  '/admin/reviews/import': typeof AdminReviewsImportRoute
  '/admin/reviews/': typeof AdminReviewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/archive'
    | '/auth'
    | '/best-new'
    | '/contact'
    | '/masthead'
    | '/radio'
    | '/reset-password'
    | '/admin/contributors'
    | '/admin/features'
    | '/admin/lists'
    | '/admin/roles'
    | '/admin/subscribers'
    | '/features/$slug'
    | '/lists/$slug'
    | '/reviews/$slug'
    | '/features/'
    | '/lists/'
    | '/reviews/'
    | '/admin/reviews/$id'
    | '/admin/reviews/import'
    | '/admin/reviews/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/archive'
    | '/auth'
    | '/best-new'
    | '/contact'
    | '/masthead'
    | '/radio'
    | '/reset-password'
    | '/admin/contributors'
    | '/admin/features'
    | '/admin/lists'
    | '/admin/roles'
    | '/admin/subscribers'
    | '/features/$slug'
    | '/lists/$slug'
    | '/reviews/$slug'
    | '/features'
    | '/lists'
    | '/reviews'
    | '/admin/reviews/$id'
    | '/admin/reviews/import'
    | '/admin/reviews'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/archive'
    | '/auth'
    | '/best-new'
    | '/contact'
    | '/masthead'
    | '/radio'
    | '/reset-password'
    | '/admin/contributors'
    | '/admin/features'
    | '/admin/lists'
    | '/admin/roles'
    | '/admin/subscribers'
    | '/features/$slug'
    | '/lists/$slug'
    | '/reviews/$slug'
    | '/features/'
    | '/lists/'
    | '/reviews/'
    | '/admin/reviews/$id'
    | '/admin/reviews/import'
    | '/admin/reviews/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ArchiveRoute: typeof ArchiveRoute
  AuthRoute: typeof AuthRoute
  BestNewRoute: typeof BestNewRoute
  ContactRoute: typeof ContactRoute
  MastheadRoute: typeof MastheadRoute
  RadioRoute: typeof RadioRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  FeaturesSlugRoute: typeof FeaturesSlugRoute
  ListsSlugRoute: typeof ListsSlugRoute
  ReviewsSlugRoute: typeof ReviewsSlugRoute
  FeaturesIndexRoute: typeof FeaturesIndexRoute
  ListsIndexRoute: typeof ListsIndexRoute
  ReviewsIndexRoute: typeof ReviewsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radio': {
      id: '/radio'
      path: '/radio'
      fullPath: '/radio'
      preLoaderRoute: typeof RadioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masthead': {
      id: '/masthead'
      path: '/masthead'
      fullPath: '/masthead'
      preLoaderRoute: typeof MastheadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best-new': {
      id: '/best-new'
      path: '/best-new'
      fullPath: '/best-new'
      preLoaderRoute: typeof BestNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/': {
      id: '/reviews/'
      path: '/reviews'
      fullPath: '/reviews/'
      preLoaderRoute: typeof ReviewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists/': {
      id: '/lists/'
      path: '/lists'
      fullPath: '/lists/'
      preLoaderRoute: typeof ListsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/': {
      id: '/features/'
      path: '/features'
      fullPath: '/features/'
      preLoaderRoute: typeof FeaturesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/$slug': {
      id: '/reviews/$slug'
      path: '/reviews/$slug'
      fullPath: '/reviews/$slug'
      preLoaderRoute: typeof ReviewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists/$slug': {
      id: '/lists/$slug'
      path: '/lists/$slug'
      fullPath: '/lists/$slug'
      preLoaderRoute: typeof ListsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/$slug': {
      id: '/features/$slug'
      path: '/features/$slug'
      fullPath: '/features/$slug'
      preLoaderRoute: typeof FeaturesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/subscribers': {
      id: '/admin/subscribers'
      path: '/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof AdminSubscribersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lists': {
      id: '/admin/lists'
      path: '/lists'
      fullPath: '/admin/lists'
      preLoaderRoute: typeof AdminListsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/features': {
      id: '/admin/features'
      path: '/features'
      fullPath: '/admin/features'
      preLoaderRoute: typeof AdminFeaturesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contributors': {
      id: '/admin/contributors'
      path: '/contributors'
      fullPath: '/admin/contributors'
      preLoaderRoute: typeof AdminContributorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews/': {
      id: '/admin/reviews/'
      path: '/reviews'
      fullPath: '/admin/reviews/'
      preLoaderRoute: typeof AdminReviewsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews/import': {
      id: '/admin/reviews/import'
      path: '/reviews/import'
      fullPath: '/admin/reviews/import'
      preLoaderRoute: typeof AdminReviewsImportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews/$id': {
      id: '/admin/reviews/$id'
      path: '/reviews/$id'
      fullPath: '/admin/reviews/$id'
      preLoaderRoute: typeof AdminReviewsIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminContributorsRoute: typeof AdminContributorsRoute
  AdminFeaturesRoute: typeof AdminFeaturesRoute
  AdminListsRoute: typeof AdminListsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSubscribersRoute: typeof AdminSubscribersRoute
  AdminReviewsIdRoute: typeof AdminReviewsIdRoute
  AdminReviewsImportRoute: typeof AdminReviewsImportRoute
  AdminReviewsIndexRoute: typeof AdminReviewsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminContributorsRoute: AdminContributorsRoute,
  AdminFeaturesRoute: AdminFeaturesRoute,
  AdminListsRoute: AdminListsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSubscribersRoute: AdminSubscribersRoute,
  AdminReviewsIdRoute: AdminReviewsIdRoute,
  AdminReviewsImportRoute: AdminReviewsImportRoute,
  AdminReviewsIndexRoute: AdminReviewsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ArchiveRoute: ArchiveRoute,
  AuthRoute: AuthRoute,
  BestNewRoute: BestNewRoute,
  ContactRoute: ContactRoute,
  MastheadRoute: MastheadRoute,
  RadioRoute: RadioRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  FeaturesSlugRoute: FeaturesSlugRoute,
  ListsSlugRoute: ListsSlugRoute,
  ReviewsSlugRoute: ReviewsSlugRoute,
  FeaturesIndexRoute: FeaturesIndexRoute,
  ListsIndexRoute: ListsIndexRoute,
  ReviewsIndexRoute: ReviewsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
